#!/usr/bin/env python3
"""
gen-api-map.py
Scans ChaosForge C# source → docs/backend-api-map.md
Extracts: response DTOs, request body types, Minimal API routes.
Replaces ~50 investigator tool calls with 1 Read.
"""

import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC = ROOT / "src"
OUT = ROOT / "docs" / "backend-api-map.md"

CS_TO_TS: dict[str, str] = {
    "Guid": "string",
    "string": "string",
    "int": "number",
    "long": "number",
    "float": "number",
    "double": "number",
    "decimal": "number",
    "bool": "boolean",
    "DateTime": "string",
    "DateOnly": "string",
    "TimeOnly": "string",
    "object": "unknown",
    "void": "void",
}


def cs_type_to_ts(cs: str) -> str:
    cs = cs.strip()
    nullable = cs.endswith("?")
    if nullable:
        cs = cs[:-1]
    m = re.match(r"(?:IEnumerable|IList|List|IReadOnlyList|ICollection)<(.+)>$", cs)
    if m:
        ts = f"{cs_type_to_ts(m.group(1))}[]"
    elif cs.endswith("[]"):
        ts = f"{cs_type_to_ts(cs[:-2])}[]"
    else:
        ts = CS_TO_TS.get(cs, cs)
    return f"{ts} | null" if nullable else ts


def camel(name: str) -> str:
    return name[0].lower() + name[1:] if name else name


def parse_record_params(raw: str) -> list[tuple[str, str]]:
    fields: list[tuple[str, str]] = []
    for param in raw.split(","):
        param = param.strip()
        if not param:
            continue
        parts = param.split()
        if len(parts) >= 2:
            fields.append((camel(parts[-1]), cs_type_to_ts(parts[0])))
    return fields


def extract_records(src: Path, suffix: str) -> list[dict]:
    records: list[dict] = []
    seen: set[str] = set()
    for cs_file in src.rglob("*.cs"):
        text = cs_file.read_text(encoding="utf-8", errors="ignore")
        for m in re.finditer(
            rf"public\s+(?:sealed\s+)?record\s+(\w+{re.escape(suffix)})\s*\(([^)]+)\)",
            text,
            re.DOTALL,
        ):
            name = m.group(1)
            if name in seen:
                continue
            seen.add(name)
            fields = parse_record_params(m.group(2))
            if fields:
                records.append({"name": name, "fields": fields, "file": cs_file.name})
    return sorted(records, key=lambda r: r["name"])


def extract_routes(endpoint_dir: Path) -> list[dict]:
    routes: list[dict] = []
    for cs_file in sorted(endpoint_dir.glob("*Endpoints.cs")):
        text = cs_file.read_text(encoding="utf-8", errors="ignore")

        gm = re.search(r'\.MapGroup\("([^"]+)"\)', text)
        base = gm.group(1) if gm else ""

        # Split on each group.MapXxx call
        for block in re.split(r"(?=group\.Map(?:Get|Post|Put|Patch|Delete))", text):
            mm = re.match(
                r'group\.Map(Get|Post|Put|Patch|Delete)\(\s*"([^"]*)"',
                block,
                re.IGNORECASE,
            )
            if not mm:
                continue

            http_method = mm.group(1).upper()
            sub_route = mm.group(2)
            path = (base + sub_route).replace("//", "/")

            body_m = re.search(r"(\w+Request)\s+\w+", block)
            body = body_m.group(1) if body_m else "—"

            op_m = re.search(r"new\s+(\w+(?:Query|Command))\s*\(", block)
            op = op_m.group(1) if op_m else "?"

            routes.append({"method": http_method, "path": path, "body": body, "op": op})

    return routes


def render(dtos: list[dict], requests: list[dict], routes: list[dict]) -> str:
    lines = [
        "# Backend API Map",
        "",
        "> Auto-generated by `tools/gen-api-map.py` — do not edit manually.",
        "> Regenerate: `python tools/gen-api-map.py`",
        "",
        "---",
        "",
        "## Response DTOs",
        "",
        "All fields `readonly`. Enum fields shown as C# name — implement as TS string literal unions.",
        "",
    ]

    for dto in dtos:
        lines.append(f"### {dto['name']}  _(from {dto['file']})_")
        lines.append("")
        lines.append("| field | TS type |")
        lines.append("|-------|---------|")
        for field, ts in dto["fields"]:
            lines.append(f"| `{field}` | `{ts}` |")
        lines.append("")

    lines += [
        "---",
        "",
        "## Request Body Types",
        "",
        "Sent as JSON. Fields are camelCase.",
        "",
    ]

    for req in requests:
        lines.append(f"### {req['name']}  _(from {req['file']})_")
        lines.append("")
        lines.append("| field | TS type |")
        lines.append("|-------|---------|")
        for field, ts in req["fields"]:
            lines.append(f"| `{field}` | `{ts}` |")
        lines.append("")

    lines += [
        "---",
        "",
        "## Routes",
        "",
        "| method | path | body type | operation |",
        "|--------|------|-----------|-----------|",
    ]
    for r in routes:
        lines.append(f"| `{r['method']}` | `{r['path']}` | `{r['body']}` | `{r['op']}` |")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    endpoint_dir = SRC / "ChaosForge.API" / "Endpoints"
    if not endpoint_dir.exists():
        print(f"ERROR: {endpoint_dir} not found", flush=True)
        raise SystemExit(1)

    print(f"Scanning {SRC}...", flush=True)
    dtos = extract_records(SRC, "Dto")
    requests = extract_records(SRC, "Request")
    routes = extract_routes(endpoint_dir)

    OUT.write_text(render(dtos, requests, routes), encoding="utf-8")
    print(f"OK {len(dtos)} DTOs  {len(requests)} request types  {len(routes)} routes -> {OUT}")

    missing_ops = [r for r in routes if r["op"] == "?"]
    if missing_ops:
        print(f"WARN {len(missing_ops)} routes with unresolved operation:")
        for r in missing_ops:
            print(f"  {r['method']} {r['path']}")


if __name__ == "__main__":
    main()
